.. _api_documentation:

API documentation
--------------------

The package contains the following modules:

* :ref:`qc_api`: Perform quality control analysis
* :ref:`utils_api`: Includes helper functions
* :ref:`wave_api`: Calculate quantities of interest for wave energy converters (WEC)
* :ref:`river_api`: Calculate quantities of interest for river energy converters (REC)
* :ref:`tidal_api`: Calculate quantities of interest for tidal energy converters (TEC)

.. include:: apidoc/api.qc.inc

.. include:: apidoc/api.utils.inc

.. include:: apidoc/api.wave.inc

.. include:: apidoc/api.river.inc

.. include:: apidoc/api.tidal.inc




