.. raw:: html

    <hr style="height:4px;border:none;color:#4682b4;background-color:#4682b4;" />

.. _api_documentation:

API documentation
--------------------

.. include:: mhkit-python/apidoc/api.qc.inc

.. include:: mhkit-python/apidoc/api.wave.inc

.. include:: mhkit-python/apidoc/api.river.inc

.. include:: mhkit-python/apidoc/api.tidal.inc

.. include:: mhkit-python/apidoc/api.utils.inc



