.. raw:: html

    <hr style="height:4px;border:none;color:#4682b4;background-color:#4682b4;" />

.. _utils:

Utils Module
--------------------

The :class:`~mhkit.utils` module contains helper functions.  Currently, the module contains a single function to help users 
convert numeric indexes to datetime indexes.  Additional helper functions could be added at a later date.

.. autosummary::

   ~mhkit.utils.index_to_datetime
 
