name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_PAGES_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Delete All Previews
        run: |
          git clone --single-branch --branch gh-pages git@github.com:MHKiT-Software/MHKiT.git gh-pages
          cd gh-pages
          rm -rf pr-previews/
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A
          git commit -m "Remove all previews after merging PR #${{ github.event.pull_request.number }}" || echo "No cleanup needed"
          git push
