name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - automate_docs
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mhkit-docs
          environment-file: environment.yml
          auto-activate-base: false

      - name: Build Documentation
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          make html
          # Move the built docs up to the docs directory
          cp -r build/html/* .

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/automate_docs')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
